services:
  - type: web
    name: bio-remove-bot
    env: python
    runtime: python-3.10         # ✅ Yeh line add karo
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
